In [2]:
# Data imputation with Visualization
import pandas as pd
import numpy as np
import random
import matplotlib.pyplot as plt
import seaborn as sns
from sklearn.impute import SimpleImputer

In [3]:
# 1. Create sample dataset
data= {
    "id" : [1,2,3,4,5,6], 
    "age" : [25,np.nan,30,35,np.nan,100],      # include Nan value
    "salary" : [50000, 60000, np.nan, 80000, 90000, np.nan],
    "city" : ["New York", "London", np.nan, "Paris", "London", np.nan]
}
df= pd.DataFrame(data)
print("original Data:")
display(df)

original Data:

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2    NaN  60000.0    London
2   3   30.0      NaN       NaN
3   4   35.0  80000.0     Paris
4   5    NaN  90000.0    London
5   6  100.0      NaN       NaN

In [4]:
# 2. Mean Imputation
mean_imputer = SimpleImputer(strategy="mean")
df_mean = df.copy()
df_mean[['age', 'salary']] = mean_imputer.fit_transform (df_mean[['age','salary']])
print('\nMean Imputed Data:')
display(df_mean)

Mean Imputed Data:

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2   47.5  60000.0    London
2   3   30.0  70000.0       NaN
3   4   35.0  80000.0     Paris
4   5   47.5  90000.0    London
5   6  100.0  70000.0       NaN

In [5]:
# 3. Median Imputation
median_imputer = SimpleImputer(strategy="median")
df_median = df.copy()
df_median[['age', 'salary']] = median_imputer.fit_transform (df_median[['age','salary']])
print('\nMedian Imputed Data:')
display(df_median)

Median Imputed Data:

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2   32.5  60000.0    London
2   3   30.0  70000.0       NaN
3   4   35.0  80000.0     Paris
4   5   32.5  90000.0    London
5   6  100.0  70000.0       NaN

In [6]:
# 4. Mode Imputation(works for both num + cat)
mode_imputer = SimpleImputer(strategy="most_frequent")
df_mode = df.copy()
df_mode[['age', 'salary','city']] = mode_imputer.fit_transform (df_mode[['age','salary','city']])
print('\nMode Imputed Data:')
display(df_mode)

Mode Imputed Data:

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2   25.0  60000.0    London
2   3   30.0  50000.0    London
3   4   35.0  80000.0     Paris
4   5   25.0  90000.0    London
5   6  100.0  50000.0    London

In [7]:
# 5. Random Sampling Imputation
df_random =df.copy()
def random_impute(series):
    # Drop Nan Values to avoid errors
    filled = series.dropna().tolist()
    return series.apply(lambda x: random.choice(filled)
    if pd.isnull(x) else x)
for col in ['age', 'salary', 'city']:
    df_random[col] = random_impute(df_random[col])

print("\nRandom Sampling Imputed Data:")
display(df_random)

Random Sampling Imputed Data:

   id    age   salary      city
0   1   25.0  50000.0  New York
1   2   25.0  60000.0    London
2   3   30.0  80000.0  New York
3   4   35.0  80000.0     Paris
4   5   30.0  90000.0    London
5   6  100.0  60000.0  New York